### ISSUE TITLE
fix macos build

### ISSUE THREAD

**Issue by source-c** [andrewchambers/janet-pq#7]
on MacOS (especialy for arm64) there is an error saying:

> compiling pq.c to build/pq.o...
pq.c:347:31: error: implicitly declaring library function 'floor' with type 'double (double)' [-Werror,-Wimplicit-function-declaration]
      const char *fmt = (d == floor(d) && d <= ((double)INT32_MAX) &&
                              ^
pq.c:347:31: note: include the header <math.h> or explicitly provide a declaration for 'floor'
1 error generated.

to avoid this - conditional include to be added, like:

```
diff --git a/pq.c b/pq.c
index af933b8..c9b8473 100644
--- a/pq.c
+++ b/pq.c
@@ -3,6 +3,10 @@
 #include <janet.h>
 #include <libpq-fe.h>

+#if defined(__APPLE_CC__)
+#include <math.h>
+#endif
+
 typedef struct {
   PGresult *r;
 } JPQresult;
```

**Comment by andrewchambers** [comment]
thank you

**Comment by source-c** [comment]
u2. `jpm install pq` now works like a charm.
